---
abstract: 'Returns information about languages.'
author:
  - 'Martin Majlis <martin@majlis.cz>'
build_requires:
  English: 0
  File::Basename: 0
  Test::Exception: 0
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.112150'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-YALI
requires:
  Carp: 0
  File::Glob: 0
  File::ShareDir: 0
  Moose: 0
  PerlIO::gzip: 0
  bytes: 0
  strict: 0
  warnings: 0
version: 0.003
