---
abstract: 'YALI - Yet Another Language Identifier.'
author:
  - 'Martin Majlis <martin@majlis.cz>'
build_requires:
  English: 1.04
  Test::Command: 0.08
  Test::Exception: 0.31
  Test::More: 0.98
  Time::HiRes: 1.9725
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-YALI
requires:
  Carp: 1.26
  File::Basename: 2.83
  File::Glob: 1.13
  File::ShareDir: 1.03
  Getopt::Long: 2.38
  List::MoreUtils: 0.33
  Moose: 2.0602
  Moose::Util::TypeConstraints: 2.0602
  POSIX: 1.26
  PerlIO::gzip: 0.18
  Pod::Usage: 1.51
  bytes: 1.04
  strict: 1.04
  warnings: 1.12
version: 0.009_02
